@startuml

actor Bob #red
' The only difference between actor
' and participant is the drawing
' - this is comment
participant Alice
participant "I have a really\nlong name" as L #99FF99
/'
    You can also declare:
    participant L as "I have a really\nlong name" as L #99FF99
'/

Alice -> Bob: Auth request
Bob -> Alice: auth response
Bob -> L: Log transaction

@enduml